services:
  namenode:
    image: hadoop:1
    container_name: hadoop-master   # = host name = core-site 
    ports:
      - 10000:10000 
      - 8088:8088    # ui yarn
      - 4040:4040   # ui spark 
      - 9870:9870   # ui name node  
    tty: true
    networks:
        cluster-hadoop:
          ipv4_address: 172.25.0.2

  datanode1:
    image: hadoop:1
    container_name: hadoop-slave1   # phai tuong ung voi file worker ben trong 
    tty: true
    networks:
        cluster-hadoop:
          ipv4_address: 172.25.0.3

  datanode2:
    image: hadoop:1
    container_name: hadoop-slave2 
    tty: true
    networks:
        cluster-hadoop:
          ipv4_address: 172.25.0.4

networks:
    cluster-hadoop:
        name: custom_network
        driver: bridge
        ipam:
          driver: default
          config:
            - subnet: 172.25.0.0/16
