services:
  platinum:
    image: docker.elastic.co/elasticsearch/elasticsearch:${VERSION:-7.17.1}
    hostname: elasticsearch-platinum
    environment:
      - cluster.name=platinum
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.license.self_generated.type=trial
      - xpack.security.enabled=true
      - xpack.watcher.enabled=true
      # - http.publish_host=localhost
      # - http.host=0.0.0.0
      # - transport.host=127.0.0.1
      # - network.host=_local_
      #- http.port=9210
      #- network.publish_host=127.0.0.1
      - logger.org.elasticsearch=warn
      - path.repo=/usr/share/elasticsearch/backup
      #- "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - ELASTIC_PASSWORD=elastic
      - ELASTICSEARCH_USERNAME=elastic
    ulimits:
      nproc: 65536
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/backup:/usr/share/elasticsearch/backup
    ports:
      - 9200:9200
    networks:
       hadoop: 
        ipv4_address: 172.25.0.5
  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.1
    container_name: kibana
    # restart: always
    environment:
      - xpack.security.enabled=true
      - 'ELASTICSEARCH_HOSTS=["http://elasticsearch-platinum:9200"]'
      - "SERVER_NAME=localhost"
      - "SERVER_PUBLICBASEURL=http://localhost:5601"
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=elastic
    ports:
      - "5601:5601"
    networks:
       hadoop: 
        ipv4_address: 172.25.0.6
networks:
    hadoop:
        name: custom_network
        driver: bridge
        ipam:
          driver: default
          config:
            - subnet: 172.25.0.0/16
