services:
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    # restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    networks:
      hadoop:
        ipv4_address: 172.25.0.9
  kafka1:
    container_name: kafka1
    image: confluentinc/cp-kafka:latest
    # restart: always
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
      - 9092:9092
    networks:
      hadoop: 
        ipv4_address: 172.25.0.10
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.233.209:9092,PLAINTEXT_HOST://192.168.233.209:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2

  kafka2:
    container_name: kafka2
    image: confluentinc/cp-kafka:latest
    # restart: always
    depends_on:
      - zookeeper
    ports:
      - 29093:29093
      - 9093:9093
    networks:
      hadoop: 
        ipv4_address: 172.25.0.11
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.233.209:9093,PLAINTEXT_HOST://192.168.233.209:29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
  
networks:
    hadoop:
        name: custom_network
        driver: bridge
        ipam:
          driver: default
          config:
            - subnet: 172.25.0.0/16
