services:
  redis:
    image: redislabs/redisearch:latest
    ports:
       - "6379:6379"
    networks:
       hadoop: 
        ipv4_address: 172.25.0.7
networks:
    hadoop:
        name: custom_network
        driver: bridge
        ipam:
          driver: default
          config:
            - subnet: 172.25.0.0/16
